version: '3.8'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile-backend
    ports:
      - "9999:9999"
    networks:
      - wordle-net

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    networks:
      - wordle-net

networks:
  wordle-net:
