# Use an official Node runtime as a parent image
FROM node:16 as build

# Set the working directory in the container
WORKDIR /app

# Copy package.json and install dependencies
COPY ./wordle-frontend/package*.json ./
RUN npm install

# Bundle app source
COPY ./wordle-frontend/ .

# Build the application
RUN npm run build

# Production environment
FROM nginx:stable-alpine
COPY --from=build /app/dist /usr/share/nginx/html
EXPOSE 5173
CMD ["nginx", "-g", "daemon off;"]
